
marvelsyncconfig:
  page-size: 100
  default-characters:
    - Iron man
    - Captain America

spring:
  data:
    mongodb:
      uri: mongodb+srv://marvel-exam:test@mongodb-sqhsj.gcp.mongodb.net/test?retryWrites=true&w=majority

marvel-api:
  config:
    ts: 1580509839
    apiKey: 9734f28553d7a122f1bb9e75c9fe6dc7
    hash: 627156470307b0e924b70546855e5462
  characters-path: https://gateway.marvel.com/v1/public/characters
  comics-path: https://gateway.marvel.com/v1/public/comics